spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: ${MYSQL_URL:jdbc:mysql://localhost:3306/linfengcommunity?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false}
            username: ${MYSQL_USERNAME:linfengcommunity}
            password: ${MYSQL_PASSWORD:linfengcommunity}
            initial-size: ${MYSQL_INITIAL_SIZE:10}
            max-active: ${MYSQL_MAX_ACTIVE:100}
            min-idle: ${MYSQL_MIN_IDLE:10}
            max-wait: ${MYSQL_MAX_WAIT:60000}
            pool-prepared-statements: ${MYSQL_POOL_PREPARED_STATEMENTS:true}
            max-pool-prepared-statement-per-connection-size: ${MYSQL_MAX_PPS_PER_CONNECTION:20}
            time-between-eviction-runs-millis: ${MYSQL_EVICTION_RUN_INTERVAL:60000}
            min-evictable-idle-time-millis: ${MYSQL_MIN_EVICTABLE_IDLE_TIME:300000}
            test-while-idle: ${MYSQL_TEST_WHILE_IDLE:true}
            test-on-borrow: ${MYSQL_TEST_ON_BORROW:false}
            test-on-return: ${MYSQL_TEST_ON_RETURN:false}
            stat-view-servlet:
                enabled: ${DRUID_STAT_ENABLED:true}
                url-pattern: ${DRUID_STAT_URL_PATTERN:/druid/*}
                login-username: ${DRUID_LOGIN_USERNAME:linfengcommunity}
                login-password: ${DRUID_LOGIN_PASSWORD:linfengtech}
            filter:
                stat:
                    log-slow-sql: ${DRUID_LOG_SLOW_SQL:true}
                    slow-sql-millis: ${DRUID_SLOW_SQL_MILLIS:1000}
                    merge-sql: ${DRUID_MERGE_SQL:false}
                wall:
                    config:
                        multi-statement-allow: ${DRUID_MULTI_STATEMENT_ALLOW:true}
    output:
      ansi:
        enabled: never   #禁止生产环境输出彩色日志
# 本地文件存储路径
# 注意：请在后台管理端配置文件存储信息
# 私聊模块的数据都是走本地存储，其他功能模块可自主选择存储方式（不推荐用本地存储）
linfeng:
  path:
    image: ${LINFENG_IMAGE_PATH:/data/linfeng/image/}
    video: ${LINFENG_VIDEO_PATH:/data/linfeng/video/}
    file: ${LINFENG_FILE_PATH:/data/linfeng/file/}

#swagger基本配置
swagger:
  title: ${SWAGGER_TITLE:慢热项目}
  version: ${SWAGGER_VERSION:3.1.0}
  basic:
      enable: ${SWAGGER_BASIC_ENABLE:true} # true开启账号密码校验，false不开启校验
      username: ${SWAGGER_BASIC_USERNAME:linfengcommunity}
      password: ${SWAGGER_BASIC_PASSWORD:linfengcommunity}

logging:
  level:
    io.linfeng: Info
    org.springframework.web: Info
    io.swagger.*: ERROR

#logging:
#  level:
#    io.linfeng: DEBUG
#    org.springframework.web: DEBUG
#    io.swagger.*: ERROR
